# Generated by Django 6.0.2 on 2026-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_tag_product_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"], "verbose_name_plural": "Tags"},
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="products.tag"),
        ),
    ]
